version: 2.1
jobs:

  build-and-test:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/xml-report/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  Mobiquity QA Coding Challenge:
    jobs:
      - build-and-test

















