version: 2.1
jobs:

  build-and-test:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn verify
workflows:
  sample:
    jobs:
      - build-and-test

















